language: python

cache:
  - bundler
  - pip

python:
  - 2.7
  - 3.5
  - 3.6
  # - 3.7
  - nightly
  # - pypy
  # - pypy3

addons:
  apt:
    packages:
      - libpcap-dev
      - libsctp-dev
      - libncurses5-dev
      - libssl-dev
      - libgsl0-dev

install:
  - pip install -e .
  - pip install --upgrade pytest
  - pip list

before_script:
  - wget https://github.com/SIPp/sipp/releases/download/v3.6.0/sipp-3.6.0.tar.gz
  - tar -xvzf sipp-3.6.0.tar.gz
  - cd sipp-3.6.0
  - ./configure
  - make
  - export PATH="$PWD:$PATH"
  - cd ..

script:
  - pytest tests/
